=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/Estudio en casa/REPASO PROYECTO 1/concesionario_coches.dtd
<!ELEMENT concesionario (informacion, stock)>
    <!ELEMENT informacion (nombre, ciudad)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT stock (coche+)>
    <!ELEMENT coche (marca, modelo, potencia, precio)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST coche
    id ID #REQUIRED
    etiqueta CDATA #REQUIRED
    color CDATA #REQUIRED>

=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/Estudio en casa/REPASO PROYECTO 1/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "concesionario_coches.dtd">
<concesionario>
  <informacion>
    <nombre>MotorSport Elite</nombre>
    <ciudad>Madrid</ciudad>
  </informacion>

  <stock>
    <coche id="C-01" etiqueta="ECO" color="rojo">
      <marca>Toyota</marca>
      <modelo>GR Yaris</modelo>
      <precio>38000</precio>
      <potencia>261</potencia>
    </coche>

    <coche id="C-02" etiqueta="C" color="negro">
      <marca>Porsche</marca>
      <modelo>911 GT3</modelo>
      <precio>210000</precio>
      <potencia>510</potencia>
    </coche>

    <coche id="C-03" etiqueta="0" color="rojo">
      <marca>Tesla</marca>
      <modelo>Model S Plaid</modelo>
      <precio>130000</precio>
      <potencia>1020</potencia>
    </coche>
  </stock>
</concesionario>
