=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/Estudio en casa/REPASO PROYECTO 1/desarrollo_coches.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="ciudad" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="stock">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="coche" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="marca" type="xs:string"/>
                                        <xs:element name="modelo" type="xs:string"/>
                                        <xs:element name="precio" type="xs:decimal"/>
                                        <xs:element name="potencia" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="etiqueta" type="xs:string" use="required"/>
                                    <xs:attribute name="color" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/Estudio en casa/REPASO PROYECTO 1/coches_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="concesionario_coches.xsl"?>

<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="desarrollo_coches.xsd">

  <informacion>
    <nombre>MotorSport Elite</nombre>
    <ciudad>Madrid</ciudad>
  </informacion>

  <stock>
    <coche id="C-01" etiqueta="ECO" color="rojo">
      <marca>Toyota</marca>
      <modelo>GR Yaris</modelo>
      <precio>38000</precio>
      <potencia>261</potencia>
    </coche>

    <coche id="C-02" etiqueta="C" color="negro">
      <marca>Porsche</marca>
      <modelo>911 GT3</modelo>
      <precio>210000</precio>
      <potencia>510</potencia>
    </coche>
  </stock>

</concesionario>
