<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales [
    <!ELEMENT animales (tipos)>
    <!ELEMENT tipos (perros, gatos)>
    <!ELEMENT perros (perro+)>
    <!ELEMENT perro (raza, peso, color)>
    <!ELEMENT gatos (gato+)>
    <!ELEMENT gato (raza, peso, color)>
    <!ELEMENT raza (#PCDATA)>
    <!ELEMENT peso (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
]>


<animales>
    <tipos>
        <perros>
            <perro>
                <raza>caniche</raza>
                <peso>4</peso>
                <color>blanco</color>
            </perro>
            <perro>
                <raza>pekines</raza>
                <peso>5</peso>
                <color>marron</color>
            </perro>
        </perros>
        <gatos>
            <gato>
                <raza>siames</raza>
                <peso>3</peso>
                <color>gris</color>
            </gato>
            <gato>
                <raza>persa</raza>
                <peso>2</peso>
                <color>negro</color>
            </gato>
        </gatos>
    </tipos>
</animales>