=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/IA/Plantillas IA/lenguaje marcas/PT1.dtd
<!ELEMENT entrenamientos (sesion+)> 

<!ELEMENT sesion (fecha, horax, tipo, duracionrv, ubicacion, coach, participantes, ejercicios?, notas?)>
<!ATTLIST sesion 
          codigo CDATA #REQUIRED
          intensidad (baja | media | alta) #IMPLIED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horax (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT duracionrv (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT coach (#PCDATA)>
<!ELEMENT participantes (boxeador+)>
<!ELEMENT boxeador (nombre, alias?, pais)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT ejercicios (ejercicio+)>
<!ELEMENT ejercicio (nombre, (repeticiones | duracionbloque))>
<!ELEMENT repeticiones (#PCDATA)>
<!ELEMENT duracionbloque (#PCDATA)>
<!ELEMENT notas (#PCDATA)>

=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/IA/Plantillas IA/lenguaje marcas/PT1.xml
<!DOCTYPE entrenamientos SYSTEM "PT1.dtd">

<entrenamientos>
    <sesion codigo="TR-01" intensidad="media">
        <fecha>2026-01-11</fecha>
        <horax>18:30</horax>
        <tipo>tecnica</tipo>
        <duracionrv>90</duracionrv>
        <ubicacion>Gimnasio Olimpia</ubicacion>
        <coach>Marcos</coach>
        <participantes>
            <boxeador>
                <nombre>Juan</nombre>
                <pais>España</pais>
                <alias>El Martillo</alias>
            </boxeador>
            <boxeador>
                <nombre>Luis</nombre>
                <pais>México</pais>
            </boxeador>
        </participantes>
        <ejercicios>
            <ejercicio>
                <nombre>Saco pesado</nombre>
                <repeticiones>10</repeticiones>
            </ejercicio>
            <ejercicio>
                <nombre>Sombra</nombre>
                <duracionbloque>15</duracionbloque>
            </ejercicio>
        </ejercicios>
        <notas>Mejorar el juego de pies en la siguiente sesión.</notas>
    </sesion>
</entrenamientos>
