=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/EXAMEN RECUPERACION T1/Examen pt1llmm/xml/arena.dtd
<!ELEMENT arena (edicion, fecha, sede, torneo)>
<!ELEMENT edicion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT sede (#PCDATA)>

<!ELEMENT torneo (nombre, categoria, plazas, equipos, resultado)>
<!ATTLIST torneo id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>

<!ELEMENT equipos (equipo, equipo)>
<!ELEMENT equipo (nombre, pais)>
<!ATTLIST equipo color CDATA #REQUIRED>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT resultado (#PCDATA)>
<!ATTLIST resultado ganador CDATA #REQUIRED>

=== fuentesrejonmanuel001alu-ctrl/Apuntes-Stem/LM/EXAMEN RECUPERACION T1/Examen pt1llmm/xml/arena.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arena SYSTEM "arena.dtd">
<arena>
    <edicion>2026</edicion>
    <fecha>2026-06-15</fecha>
    <sede>Costa del Sol</sede>
    
    <torneo id="SA-001">
        <nombre>Torneo Voley Playa STEM</nombre>
        <categoria>Senior</categoria>
        <plazas>32</plazas>
        
        <equipos>
            <equipo color="rojo">
                <nombre>Los Titanes</nombre>
                <pais>Espa√±a</pais>
            </equipo>
            <equipo color="azul">
                <nombre>Night Owls</nombre>
                <pais>Portugal</pais>
            </equipo>
        </equipos>
        
        <resultado ganador="Los Titanes">2-1</resultado>
    </torneo>
</arena>
